# Generated by Django 4.2 on 2023-05-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopmanagerprofile",
            name="emergency_contact",
            field=models.CharField(max_length=17),
        ),
    ]
