# Generated by Django 4.2 on 2023-04-05 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('nid', models.CharField(max_length=17)),
                ('photo', models.ImageField(upload_to='profile_photos/')),
                ('NID_front_photo', models.ImageField(upload_to='nid_photo/')),
                ('NID_back_photo', models.ImageField(upload_to='nid_photo/')),
                ('permanent_address', models.CharField(max_length=255)),
                ('present_address', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personal_contact', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
