# Generated by Django 4.2 on 2023-04-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanprofile',
            name='joining_date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
