# Generated by Django 4.2 on 2023-04-27 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("App_products", "0010_alter_productmodel_barcode_id"),
        ("App_seller", "0003_customerprofile_ordermodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="products_n_quantity",
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-04-28 10:30:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="App_seller.customerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="CartItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="App_products.productmodel",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="items",
            field=models.ManyToManyField(to="App_seller.cartitemmodel"),
        ),
    ]
