# Generated by Django 4.2 on 2023-04-27 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("App_seller", "0003_customerprofile_ordermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="totalPrice",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="seller_name",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
