# Generated by Django 4.1 on 2023-04-28 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_products', '0010_alter_productmodel_barcode_id'),
        ('App_seller', '0004_remove_ordermodel_products_n_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.CreateModel(
            name='StockAlertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_products.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiryAlertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_products.productmodel')),
            ],
        ),
    ]
