# Generated by Django 4.1 on 2023-04-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_seller', '0005_alter_customerprofile_phone_number_stockalertmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
