# Generated by Django 4.1.2 on 2023-04-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_seller', '0006_cartitemmodel_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=200),
            preserve_default=False,
        ),
    ]
