# Generated by Django 4.2 on 2023-05-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_seller", "0007_ordermodel_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesmanprofile",
            name="employee_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
