# Generated by Django 4.2 on 2023-05-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_seller", "0008_alter_salesmanprofile_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesmanprofile",
            name="nid",
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
