# Generated by Django 4.2 on 2023-05-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_seller", "0009_alter_salesmanprofile_nid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesmanprofile",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
