# Generated by Django 4.2 on 2023-04-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="type",
            field=models.CharField(default="Tablet", max_length=255),
        ),
    ]
