# Generated by Django 4.2 on 2023-04-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_products', '0002_productmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
