# Generated by Django 4.2 on 2023-04-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_products', '0003_productmodel_imported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelf_number', to='App_products.shelf'),
        ),
    ]
