# Generated by Django 4.2 on 2023-04-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_products", "0004_alter_productmodel_shelf"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="importer",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
