# Generated by Django 4.2 on 2023-04-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_products', '0006_alter_productmodel_importer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='bought_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
