# Generated by Django 4.2 on 2023-04-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_products", "0007_alter_productmodel_bought_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="product_id",
        ),
        migrations.AddField(
            model_name="productmodel",
            name="barcode_id",
            field=models.CharField(default="None", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
