# Generated by Django 4.2 on 2023-04-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_products", "0008_remove_productmodel_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="Pharmacology",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
