# Generated by Django 4.2 on 2023-04-30 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App_products", "0011_productconsumptiontypemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="type",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="consumption_type",
                to="App_products.productconsumptiontypemodel",
            ),
        ),
    ]
